/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonAppearance, ButtonSize } from "./components/types";
export namespace Components {
    interface McButton {
        /**
          * The appearance of the button, according to the Themes defined.
         */
        "appearance": ButtonAppearance;
        /**
          * Whether the button is disabled.
         */
        "disabled": boolean;
        /**
          * Should the button grow full width.
         */
        "fullWidth": boolean;
        /**
          * Should the button be an icon only.
         */
        "iconOnly": boolean;
        /**
          * Text content for Aria label, mandatory when iconOnly is set to true.
         */
        "screenReaderText"?: string;
        /**
          * Button size.
         */
        "size": ButtonSize;
    }
}
declare global {
    interface HTMLMcButtonElement extends Components.McButton, HTMLStencilElement {
    }
    var HTMLMcButtonElement: {
        prototype: HTMLMcButtonElement;
        new (): HTMLMcButtonElement;
    };
    interface HTMLElementTagNameMap {
        "mc-button": HTMLMcButtonElement;
    }
}
declare namespace LocalJSX {
    interface McButton {
        /**
          * The appearance of the button, according to the Themes defined.
         */
        "appearance"?: ButtonAppearance;
        /**
          * Whether the button is disabled.
         */
        "disabled"?: boolean;
        /**
          * Should the button grow full width.
         */
        "fullWidth"?: boolean;
        /**
          * Should the button be an icon only.
         */
        "iconOnly"?: boolean;
        /**
          * Button click event.
         */
        "onClicked"?: (event: CustomEvent<any>) => void;
        /**
          * Text content for Aria label, mandatory when iconOnly is set to true.
         */
        "screenReaderText"?: string;
        /**
          * Button size.
         */
        "size"?: ButtonSize;
    }
    interface IntrinsicElements {
        "mc-button": McButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mc-button": LocalJSX.McButton & JSXBase.HTMLAttributes<HTMLMcButtonElement>;
        }
    }
}
