name: Deploy test coverage report - Web
on:
  push:
    branches:
      - 'development'
      - 'feature-devops'
    tags:
      - 'release/v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      - name: Install node modules
        run: npm i --force
      - name: Run npm version patch
        run: |
          npm version patch
          npm publish